spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/films-db
spring.datasource.username=postgres
spring.datasource.password=FILMS*

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
S